import Link from "next/link";
import { SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { redirect } from "next/navigation";
import { auth } from "@clerk/nextjs/server";

export default async function Home() {
  const { userId } = await auth();

  if (userId) {
    redirect("/dashboard");
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <nav className="max-w-6xl mx-auto px-8 py-6 flex justify-between items-center">
        <div className="text-2xl font-bold text-blue-600">Paper Reader</div>
        <div className="flex gap-4 items-center">
          <SignedOut>
            <SignInButton mode="modal">
              <button className="px-4 py-2 text-gray-700 hover:text-gray-900">
                Sign In
              </button>
            </SignInButton>
            <SignUpButton mode="modal">
              <button className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                Get Started
              </button>
            </SignUpButton>
          </SignedOut>
          <SignedIn>
            <Link href="/dashboard" className="px-4 py-2 text-gray-700 hover:text-gray-900">
              Dashboard
            </Link>
            <UserButton />
          </SignedIn>
        </div>
      </nav>

      <main className="max-w-6xl mx-auto px-8 py-20">
        <div className="text-center mb-20">
          <h1 className="text-5xl font-bold mb-6 text-gray-900">
            AI-Powered Research Paper Summaries
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Process arXiv papers with Claude AI to get concise, readable summaries.
            Save time and focus on what matters in your research.
          </p>
          <SignUpButton mode="modal">
            <button className="px-8 py-4 bg-blue-600 text-white text-lg rounded-lg hover:bg-blue-700">
              Start Processing Papers
            </button>
          </SignUpButton>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-20">
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-xl font-semibold mb-2">Instant Summaries</h3>
            <p className="text-gray-600">
              Paste an arXiv URL and get a comprehensive summary generated by Claude Opus.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-xl font-semibold mb-2">Humanized Content</h3>
            <p className="text-gray-600">
              Technical summaries are automatically humanized for easier reading and understanding.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-xl font-semibold mb-2">Your API Key</h3>
            <p className="text-gray-600">
              Use your own Anthropic API key. We encrypt and store it securely.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-8">
          <h2 className="text-2xl font-bold mb-6 text-center">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                1
              </div>
              <h4 className="font-semibold mb-2">Sign Up</h4>
              <p className="text-sm text-gray-600">
                Create your account and add your Anthropic API key
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                2
              </div>
              <h4 className="font-semibold mb-2">Submit Paper</h4>
              <p className="text-sm text-gray-600">
                Paste an arXiv URL or paper ID
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                3
              </div>
              <h4 className="font-semibold mb-2">AI Processing</h4>
              <p className="text-sm text-gray-600">
                Claude analyzes and summarizes the paper
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                4
              </div>
              <h4 className="font-semibold mb-2">Read Summary</h4>
              <p className="text-sm text-gray-600">
                Access your summary in the dashboard
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer className="max-w-6xl mx-auto px-8 py-8 text-center text-gray-600 border-t">
        <p>Paper Reader - AI-powered research assistant</p>
      </footer>
    </div>
  );
}
