export const ARXIV_CATEGORIES = [
  { section: "Computer Science", categories: [
    { id: "cs.AI", name: "Artificial Intelligence" },
    { id: "cs.LG", name: "Machine Learning" },
    { id: "cs.CV", name: "Computer Vision and Pattern Recognition" },
    { id: "cs.CL", name: "Computation and Language (NLP)" },
    { id: "cs.CR", name: "Cryptography and Security" },
    { id: "cs.RO", name: "Robotics" },
    { id: "cs.AR", name: "Hardware Architecture" },
    { id: "cs.DC", name: "Distributed, Parallel, and Cluster Computing" },
    { id: "cs.OS", name: "Operating Systems" },
    { id: "cs.NI", name: "Networking and Internet Architecture" },
    { id: "cs.PF", name: "Performance" },
    { id: "cs.SY", name: "Systems and Control" },
    { id: "cs.CC", name: "Computational Complexity" },
    { id: "cs.DS", name: "Data Structures and Algorithms" },
    { id: "cs.DM", name: "Discrete Mathematics" },
    { id: "cs.FL", name: "Formal Languages and Automata Theory" },
    { id: "cs.GT", name: "Computer Science and Game Theory" },
    { id: "cs.LO", name: "Logic in Computer Science" },
    { id: "cs.SE", name: "Software Engineering" },
    { id: "cs.PL", name: "Programming Languages" },
    { id: "cs.DB", name: "Databases" },
    { id: "cs.IR", name: "Information Retrieval" },
    { id: "cs.CG", name: "Computational Geometry" },
    { id: "cs.CY", name: "Computers and Society" },
    { id: "cs.GR", name: "Graphics" },
    { id: "cs.HC", name: "Human-Computer Interaction" },
    { id: "cs.IT", name: "Information Theory" },
    { id: "cs.MA", name: "Multiagent Systems" },
    { id: "cs.MM", name: "Multimedia" },
    { id: "cs.NE", name: "Neural and Evolutionary Computing" },
    { id: "cs.SC", name: "Symbolic Computation" },
    { id: "cs.SD", name: "Sound" },
    { id: "cs.SI", name: "Social and Information Networks" },
  ]},
  { section: "Mathematics", categories: [
    { id: "math.AG", name: "Algebraic Geometry" },
    { id: "math.AC", name: "Commutative Algebra" },
    { id: "math.GR", name: "Group Theory" },
    { id: "math.RT", name: "Representation Theory" },
    { id: "math.RA", name: "Rings and Algebras" },
    { id: "math.DG", name: "Differential Geometry" },
    { id: "math.GT", name: "Geometric Topology" },
    { id: "math.SG", name: "Symplectic Geometry" },
    { id: "math.AP", name: "Analysis of PDEs" },
    { id: "math.CA", name: "Classical Analysis and ODEs" },
    { id: "math.FA", name: "Functional Analysis" },
    { id: "math.CV", name: "Complex Variables" },
    { id: "math.SP", name: "Spectral Theory" },
    { id: "math.NA", name: "Numerical Analysis" },
    { id: "math.OC", name: "Optimization and Control" },
    { id: "math.PR", name: "Probability" },
    { id: "math.ST", name: "Statistics Theory" },
    { id: "math.DS", name: "Dynamical Systems" },
    { id: "math.CO", name: "Combinatorics" },
    { id: "math.NT", name: "Number Theory" },
    { id: "math.LO", name: "Logic" },
    { id: "math.AT", name: "Algebraic Topology" },
    { id: "math.CT", name: "Category Theory" },
    { id: "math.IT", name: "Information Theory" },
    { id: "math.MP", name: "Mathematical Physics" },
    { id: "math.QA", name: "Quantum Algebra" },
  ]},
  { section: "Physics", categories: [
    { id: "physics.comp-ph", name: "Computational Physics" },
    { id: "physics.app-ph", name: "Applied Physics" },
    { id: "physics.data-an", name: "Data Analysis, Statistics and Probability" },
    { id: "physics.class-ph", name: "Classical Physics" },
    { id: "physics.gen-ph", name: "General Physics" },
    { id: "physics.optics", name: "Optics" },
    { id: "physics.flu-dyn", name: "Fluid Dynamics" },
    { id: "physics.acc-ph", name: "Accelerator Physics" },
    { id: "physics.ao-ph", name: "Atmospheric and Oceanic Physics" },
    { id: "physics.atm-clus", name: "Atomic and Molecular Clusters" },
    { id: "physics.atom-ph", name: "Atomic Physics" },
    { id: "physics.bio-ph", name: "Biological Physics" },
    { id: "physics.chem-ph", name: "Chemical Physics" },
    { id: "physics.geo-ph", name: "Geophysics" },
    { id: "physics.ins-det", name: "Instrumentation and Detectors" },
    { id: "physics.med-ph", name: "Medical Physics" },
    { id: "physics.plasm-ph", name: "Plasma Physics" },
    { id: "physics.soc-ph", name: "Physics and Society" },
    { id: "physics.space-ph", name: "Space Physics" },
  ]},
  { section: "Statistics", categories: [
    { id: "stat.ML", name: "Machine Learning" },
    { id: "stat.AP", name: "Applications" },
    { id: "stat.CO", name: "Computation" },
    { id: "stat.ME", name: "Methodology" },
    { id: "stat.TH", name: "Statistics Theory" },
  ]},
  { section: "Quantitative Biology", categories: [
    { id: "q-bio.BM", name: "Biomolecules" },
    { id: "q-bio.CB", name: "Cell Behavior" },
    { id: "q-bio.GN", name: "Genomics" },
    { id: "q-bio.MN", name: "Molecular Networks" },
    { id: "q-bio.NC", name: "Neurons and Cognition" },
    { id: "q-bio.PE", name: "Populations and Evolution" },
    { id: "q-bio.QM", name: "Quantitative Methods" },
    { id: "q-bio.SC", name: "Subcellular Processes" },
    { id: "q-bio.TO", name: "Tissues and Organs" },
  ]},
];

export const POPULAR_CATEGORY_IDS = new Set([
  "cs.AI",
  "cs.LG",
  "cs.CV",
  "cs.CL",
  "cs.RO",
  "cs.CR",
  "cs.DB",
  "cs.SE",
]);
