export const MEDRXIV_CATEGORIES = [
  { id: "medrxiv:addiction-medicine", name: "Addiction Medicine", apiCategory: "addiction medicine" },
  { id: "medrxiv:allergy-and-immunology", name: "Allergy and Immunology", apiCategory: "allergy and immunology" },
  { id: "medrxiv:anesthesia", name: "Anesthesia", apiCategory: "anesthesia" },
  { id: "medrxiv:cardiovascular-medicine", name: "Cardiovascular Medicine", apiCategory: "cardiovascular medicine" },
  { id: "medrxiv:dentistry-and-oral-medicine", name: "Dentistry and Oral Medicine", apiCategory: "dentistry and oral medicine" },
  { id: "medrxiv:dermatology", name: "Dermatology", apiCategory: "dermatology" },
  { id: "medrxiv:emergency-medicine", name: "Emergency Medicine", apiCategory: "emergency medicine" },
  { id: "medrxiv:endocrinology-including-diabetes-mellitus-and-metabolic-disease", name: "Endocrinology (including Diabetes Mellitus and Metabolic Disease)", apiCategory: "endocrinology (including diabetes mellitus and metabolic disease)" },
  { id: "medrxiv:epidemiology", name: "Epidemiology", apiCategory: "epidemiology" },
  { id: "medrxiv:forensic-medicine", name: "Forensic Medicine", apiCategory: "forensic medicine" },
  { id: "medrxiv:gastroenterology", name: "Gastroenterology", apiCategory: "gastroenterology" },
  { id: "medrxiv:genetic-and-genomic-medicine", name: "Genetic and Genomic Medicine", apiCategory: "genetic and genomic medicine" },
  { id: "medrxiv:geriatric-medicine", name: "Geriatric Medicine", apiCategory: "geriatric medicine" },
  { id: "medrxiv:health-economics", name: "Health Economics", apiCategory: "health economics" },
  { id: "medrxiv:health-informatics", name: "Health Informatics", apiCategory: "health informatics" },
  { id: "medrxiv:health-policy", name: "Health Policy", apiCategory: "health policy" },
  { id: "medrxiv:health-systems-and-quality-improvement", name: "Health Systems and Quality Improvement", apiCategory: "health systems and quality improvement" },
  { id: "medrxiv:hematology", name: "Hematology", apiCategory: "hematology" },
  { id: "medrxiv:hiv-aids", name: "HIV/AIDS", apiCategory: "hiv/aids" },
  { id: "medrxiv:infectious-diseases", name: "Infectious Diseases (except HIV/AIDS)", apiCategory: "infectious diseases" },
  { id: "medrxiv:intensive-care-and-critical-care-medicine", name: "Intensive Care and Critical Care Medicine", apiCategory: "intensive care and critical care medicine" },
  { id: "medrxiv:medical-education", name: "Medical Education", apiCategory: "medical education" },
  { id: "medrxiv:medical-ethics", name: "Medical Ethics", apiCategory: "medical ethics" },
  { id: "medrxiv:nephrology", name: "Nephrology", apiCategory: "nephrology" },
  { id: "medrxiv:neurology", name: "Neurology", apiCategory: "neurology" },
  { id: "medrxiv:nursing", name: "Nursing", apiCategory: "nursing" },
  { id: "medrxiv:nutrition", name: "Nutrition", apiCategory: "nutrition" },
  { id: "medrxiv:obstetrics-and-gynecology", name: "Obstetrics and Gynecology", apiCategory: "obstetrics and gynecology" },
  { id: "medrxiv:occupational-and-environmental-health", name: "Occupational and Environmental Health", apiCategory: "occupational and environmental health" },
  { id: "medrxiv:oncology", name: "Oncology", apiCategory: "oncology" },
  { id: "medrxiv:ophthalmology", name: "Ophthalmology", apiCategory: "ophthalmology" },
  { id: "medrxiv:orthopedics", name: "Orthopedics", apiCategory: "orthopedics" },
  { id: "medrxiv:otolaryngology", name: "Otolaryngology", apiCategory: "otolaryngology" },
  { id: "medrxiv:pain-medicine", name: "Pain Medicine", apiCategory: "pain medicine" },
  { id: "medrxiv:palliative-medicine", name: "Palliative Medicine", apiCategory: "palliative medicine" },
  { id: "medrxiv:pathology", name: "Pathology", apiCategory: "pathology" },
  { id: "medrxiv:pediatrics", name: "Pediatrics", apiCategory: "pediatrics" },
  { id: "medrxiv:pharmacology-and-therapeutics", name: "Pharmacology and Therapeutics", apiCategory: "pharmacology and therapeutics" },
  { id: "medrxiv:primary-care-research", name: "Primary Care Research", apiCategory: "primary care research" },
  { id: "medrxiv:psychiatry-and-clinical-psychology", name: "Psychiatry and Clinical Psychology", apiCategory: "psychiatry and clinical psychology" },
  { id: "medrxiv:public-and-global-health", name: "Public and Global Health", apiCategory: "public and global health" },
  { id: "medrxiv:radiology-and-imaging", name: "Radiology and Imaging", apiCategory: "radiology and imaging" },
  { id: "medrxiv:rehabilitation-medicine-and-physical-therapy", name: "Rehabilitation Medicine and Physical Therapy", apiCategory: "rehabilitation medicine and physical therapy" },
  { id: "medrxiv:respiratory-medicine", name: "Respiratory Medicine", apiCategory: "respiratory medicine" },
  { id: "medrxiv:rheumatology", name: "Rheumatology", apiCategory: "rheumatology" },
  { id: "medrxiv:sexual-and-reproductive-health", name: "Sexual and Reproductive Health", apiCategory: "sexual and reproductive health" },
  { id: "medrxiv:sports-medicine", name: "Sports Medicine", apiCategory: "sports medicine" },
  { id: "medrxiv:surgery", name: "Surgery", apiCategory: "surgery" },
  { id: "medrxiv:toxicology", name: "Toxicology", apiCategory: "toxicology" },
  { id: "medrxiv:transplantation", name: "Transplantation", apiCategory: "transplantation" },
  { id: "medrxiv:urology", name: "Urology", apiCategory: "urology" },
];

export const MEDRXIV_CATEGORY_BY_ID = new Map(
  MEDRXIV_CATEGORIES.map((c) => [c.id, c])
);

export const MEDRXIV_CATEGORY_BY_API_NAME = new Map(
  MEDRXIV_CATEGORIES.map((c) => [c.apiCategory, c])
);
